name: Publish dev image
on:
  push:
    branches: 
      - '*' 
  pull_request:
    branches:
      - '*'

env:
  QEMU_PLATFORMS: arm64,arm
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  IMAGE_REPO: shaposhnikoff/teamcity-agent

jobs:
  build_dev_image:
    name: Dev image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Prepare environment
        run: |
          : Setup imageTag, appVersion and dockerFile envs and build image
          imageTag=${GITHUB_REF#refs/tags/}
          APP_VERSION=${imageTag}
          FINAL_IMAGE_NAME="${IMAGE_REPO}:${imageTag}"

          : Override image name and version for dev image
          # dev-feat_branch-371e2d3b-2020.02.06_18:37:42
          APP_VERSION=${GITHUB_REF#refs/heads/}-${GITHUB_SHA::8}-$(date +'%Y.%m.%d_%H:%M:%S')
          FINAL_IMAGE_NAME="${IMAGE_REPO}:pr${{ github.event.pull_request.number }}"
          : end override

          echo "FINAL_IMAGE_NAME=${FINAL_IMAGE_NAME}" >> ${GITHUB_ENV}
          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV}

          echo "========================================="
          echo "APP_VERSION        = $APP_VERSION"
          echo "FINAL_IMAGE_NAME   = $FINAL_IMAGE_NAME"
          echo "========================================="

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: "${{ env.QEMU_PLATFORMS }}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Prepare to Build
        run: |
          echo "Build $FINAL_IMAGE_NAME with version '$APP_VERSION'"
          docker run -i --rm --privileged tonistiigi/binfmt --install all

      - name: Build and push multi-arch image
        run: |
          echo "Build $FINAL_IMAGE_NAME with version '$APP_VERSION'"
          docker buildx build --push \
              --platform $BUILDX_PLATFORMS \
              --build-arg appVersion=$APP_VERSION \
              --tag $FINAL_IMAGE_NAME .

